name: Linting

on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v1

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'yarn'

            - name: Install packages w/ Yarn
              run: yarn install

            - name: Lint JS
              run: yarn lint:js

            - name: Lint CSS
              run: yarn lint:css

            - name: Lint package.json
              run: yarn lint:pkg-json

            - name: Lint Markdown docs
              run: yarn lint:md-docs
